document.writeln("");
document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">");
document.writeln("<title>鏈接安全保障 - 500福利导航</title>");
document.writeln("<meta name=\"keywords\" content=\"500导航,500福利导航,500福利导航地址,提交收录,广告合作,联系我们,500福利导航导航,500福利导航官网\">");
document.writeln("<meta name=\"description\" content=\"500导航入口首家上線鏈接安全保障賠付計劃！\">");
document.writeln("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">");
document.writeln("<meta name=\"viewport\" content=\"width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\">");
document.writeln("<meta http-equiv=\"Cache-Control\" content=\"no-transform\">");
document.writeln("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\">");
document.writeln("<meta name=\"applicable-device\" content=\"pc,mobile\">");
document.writeln("<meta name=\"MobileOptimized\" content=\"width\">");
document.writeln("<meta name=\"HandheldFriendly\" content=\"true\">");
document.writeln("<meta name=\"author\" content=\"MMWZ\">");
document.writeln("<link rel=\"stylesheet\" href=\"css/faq.css?v=2022\">");
document.writeln("<link rel=\"stylesheet\" href=\"//s2.pstatp.com/cdn/expire-1-M/font-awesome/4.7.0/css/font-awesome.min.css\">");
document.writeln("");
document.writeln("<link rel=\"shortcut icon\" href=\"favicon.ico\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div id=\"container\">");
document.writeln("<div class=\"nav\">");
document.writeln("<a href=\"../\" target=\"_self\" style=\"color:white;font-weight:bold\"><li>首 頁</li></a>");
document.writeln("<a href=\"faq.html#ads\" target=\"_blank\" style=\"color:white;font-weight:bold\"><li>合 作</li></a>");
document.writeln("<a href=\"faq.html#contact\" target=\"_blank\" style=\"color:white;font-weight:bold\"><li>聯 絡</li></a>");
document.writeln("<a href=\"faq.html#log\" target=\"_blank\" style=\"color:white;font-weight:bold\"><li>更 新</li></a>");
document.writeln("<a href=\"https://500fabu.com\" target=\"_blank\" style=\"color:white;font-weight:bold\"><li>地址發布</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<p style=\"background:#fffce7;margin:0 0 10px;padding:10px;font-size:13px;color:red;border-radius:5px;\">");
document.writeln("<span style=\"display:inline-block;background:#DA634B;color:#fff;font-weight:bold;padding:2px 8px;border-radius:2px;\"><i class=\"fa fa-bullhorn\" aria-hidden=\"true\"></i> 友情提示</span>&nbsp;&nbsp;近期500福利导航網站頻繁遭到無良小人粗暴的山寨抄襲，請訪客注意辨別真偽，以免上當受騙！");
document.writeln("</p>");
document.writeln("");
document.writeln("<div class=\"cate\" id=\"about\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-shield\" aria-hidden=\"true\"></i> 安全保障計劃</p>");
document.writeln("</div>");
document.writeln("<a><li>為了保障所有訪客的財產安全</li></a>");
document.writeln("<a><li>500福利导航網站首家上線鏈接安全保障賠付計劃</li></a>");
document.writeln("<a><li>凡是在訪問本站時遭遇的經濟損失</li></a>");
document.writeln("<a><li>將得到100%全額賠付</li></a>");
document.writeln("<a><li>讓您在訪問本站的時候免除后顧之憂！</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate\" id=\"ads\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-user\" aria-hidden=\"true\"></i> 保障范圍</p>");
document.writeln("</div>");
document.writeln("<a><li>1、不限地區的保障所有500导航的訪客;</li></a>");
document.writeln("<a><li>2、因訪問本站直接點出網址(不限于廣告鏈接)造成的人身財產損失;</li></a>");
document.writeln("<a><li>3、因訪問本站直接點出網址遭遇的電信網絡詐騙行為；</li></a>");
document.writeln("<a><li>4、因訪問本站直接點出網址造成的網站/APP等充值失敗；</li></a>");
document.writeln("<a><li>5、因訪問本站直接點出網址引發的其他未知損失；</li></a>");
document.writeln("<a><li>6、非本站直接點出網址不在保障范圍之內！</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate\" id=\"add\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-trophy\" aria-hidden=\"true\"></i> 申請賠付</p>");
document.writeln("</div>");
document.writeln("<a><li>1、整理相關材料（支付截圖/對話截圖/對方鏈接地址）;</li></a>");
document.writeln("<a><li>2、將材料及申述詳情發送至官方客服郵箱;</li></a>");
document.writeln("<a><li>3、客服將在3個工作日內與您主動聯絡溝通;</li></a>");
document.writeln("<a><li>4、經客服核實屬實后將于當日全額退款至您的帳戶！</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate\" id=\"contact\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-envelope\" aria-hidden=\"true\"></i> 賠付渠道</p>");
document.writeln("</div>");
document.writeln("<a><li>所有未盡及具體事宜，請聯繫</li></a>");
document.writeln("<a><li>電子郵箱：<span style=\"color:#003399;\">500fulidaohang@gmail.com</span></li></a>");
document.writeln("<a><li>因客服事務繁雜，請您務必郵件標題注明鏈接賠付，我們將優先處理！</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate footer\">");
document.writeln("<p>CopyRight&nbsp;&nbsp;©&nbsp;&nbsp;500dh.com</p>");
document.writeln("<p> <i class=\"fa fa-home\" aria-hidden=\"true\"></i> <a href=\"../\" class=\"aboutBtn\" target=\"_blank\">返回首頁</a>&nbsp;&nbsp;<i class=\"fa fa-shield\" aria-hidden=\"true\"></i> <a href=\"aq.html\" class=\"aboutBtn\" target=\"_blank\">安全保障</a>&nbsp;&nbsp;<i class=\"fa fa-plus-square\" aria-hidden=\"true\"></i> <a href=\"faq.html\" class=\"aboutBtn\" target=\"_blank\">收錄合作</a></p>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-238922081-3\"></script>");
document.writeln("<script>");
document.writeln("  window.dataLayer = window.dataLayer || [];");
document.writeln("  function gtag(){dataLayer.push(arguments);}");
document.writeln("  gtag(\'js\', new Date());");
document.writeln("");
document.writeln("  gtag(\'config\', \'UA-238922081-3\');");
document.writeln("</script>");
document.writeln("");
document.writeln("<!-- Global site tag (gtag.js) - Google Analytics -->");
document.writeln("<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-153452776-1\"></script>");
document.writeln("<script>");
document.writeln("  window.dataLayer = window.dataLayer || [];");
document.writeln("  function gtag(){dataLayer.push(arguments);}");
document.writeln("  gtag(\'js\', new Date());");
document.writeln("");
document.writeln("  gtag(\'config\', \'UA-153452776-1\');");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("</html>");
