document.writeln("");
document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">");
document.writeln("<title>关于/收录/广告/联繫 - 500福利导航</title>");
document.writeln("<meta name=\"keywords\" content=\"500福利导航,500导航,500福利导航地址,提交收录,广告合作,联系我们,500福利导航导航,500福利导航官网\">");
document.writeln("<meta name=\"description\" content=\"与500导航一起合作共赢！\">");
document.writeln("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">");
document.writeln("<meta name=\"viewport\" content=\"width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\">");
document.writeln("<meta http-equiv=\"Cache-Control\" content=\"no-transform\">");
document.writeln("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\">");
document.writeln("<meta name=\"applicable-device\" content=\"pc,mobile\">");
document.writeln("<meta name=\"MobileOptimized\" content=\"width\">");
document.writeln("<meta name=\"HandheldFriendly\" content=\"true\">");
document.writeln("<meta name=\"author\" content=\"MMRK\">");
document.writeln("<link rel=\"stylesheet\" href=\"css/faq.css?v=202202\">");
document.writeln("<link rel=\"stylesheet\" href=\"//s2.pstatp.com/cdn/expire-1-M/font-awesome/4.7.0/css/font-awesome.min.css\">");
document.writeln("");
document.writeln("<link rel=\"shortcut icon\" href=\"favicon.ico\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div id=\"container\">");
document.writeln("<div class=\"nav\">");
document.writeln("<a href=\"../\" target=\"_self\" style=\"color:white;font-weight:bold\"><li>首 页</li></a>");
document.writeln("<a href=\"#ads\" target=\"_self\" style=\"color:white;font-weight:bold\"><li>合 作</li></a>");
document.writeln("<a href=\"#contact\" target=\"_self\" style=\"color:white;font-weight:bold\"><li>联 络</li></a>");
document.writeln("<a href=\"#log\" target=\"_self\" style=\"color:white;font-weight:bold\"><li>更 新</li></a>");
document.writeln("<a href=\"https://500fabu.com\" target=\"_blank\" style=\"color:white;font-weight:bold\"><li>地址发布</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<p style=\"background:#fffce7;margin:0 0 10px;padding:10px;font-size:13px;color:red;border-radius:5px;\">");
document.writeln("<span style=\"display:inline-block;background:#DA634B;color:#fff;font-weight:bold;padding:2px 8px;border-radius:2px;\"><i class=\"fa fa-bullhorn\" aria-hidden=\"true\"></i> 友情提示</span>&nbsp;&nbsp;近期500福利导航网站频繁遭到无良小人粗暴的山寨抄袭，请访客注意辨别真伪，以免上当受骗！");
document.writeln("</p>");
document.writeln("");
document.writeln("<div class=\"cate\" id=\"about\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-users\" aria-hidden=\"true\"></i> 关于我们</p>");
document.writeln("</div>");
document.writeln("<a><li>500福利导航网站创建于2018年 ◕‿◕</li></a>");
document.writeln("<a><li>这裡所分享的内容都经过我们的精心挑选</li></a>");
document.writeln("<a><li>我们希望能满足您的所有需要</li></a>");
document.writeln("<a><li>所以不断整合网路上分散的福利网站</li></a>");
document.writeln("<a><li>只为让您获得最简单、最全面、最整洁的福利网址导航体验</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate\" id=\"ads\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-audio-description\" aria-hidden=\"true\"></i> 广告合作</p>");
document.writeln("</div>");
document.writeln("<a><li>1、有意在本站刊登广告，请将您的产品详情发送至客服邮箱;</li></a>");
document.writeln("<a><li>2、广告不得影响用户体验，不接受悬浮、弹窗、病毒类广告;</li></a>");
document.writeln("<a><li>3、大客户尊享<b class=\"orange\">荐</b> <b>APP</b> 图标及字体颜色定制；</li></a>");
document.writeln("<a><li>4、广告仅支持 <i class=\"fa fa-usd\" aria-hidden=\"true\"></i> USDT 或者 <i class=\"fa fa-btc\" aria-hidden=\"true\"></i> BTC结算；</li></a>");
document.writeln("<a><li>5、广告到期本站不做任何提醒，未及时续费本站有权另行处理！</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate\" id=\"add\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-handshake-o\" aria-hidden=\"true\"></i> 友链合作</p>");
document.writeln("</div>");
document.writeln("<a><li><span style=\"color:#E53333;\"><i class=\"fa fa-exclamation-triangle\" aria-hidden=\"true\"></i> 以下内容务必详细阅读，否则不会收录！</span></li></a>");
document.writeln("<a><li>1、网站名称：<font color=\"#003399\"> 500福利导航 </font> </li></a>");
document.writeln("<a><li>2、收录地址：<span style=\"color:#003399;\"><i class=\"fa fa-link\" aria-hidden=\"true\"></i> <u>https://www.500dizhi.com/</u></span> </li></a>");
document.writeln("<a><li>3、将500福利导航放置于全站友链前五位;</li></a>");
document.writeln("<a><li>4、将站点资料发送至500福利导航官方邮箱;</li></a>");
document.writeln("<a><li>5、不收录站群类站点/恶意代码站点/纯付费站点;</li></a>");
document.writeln("<a><li>6、不收录盗版假冒本站的站点;</li></a>");
document.writeln("<a><li>7、本站地址较多，您的统计来路可能不准确！</li></a>");
document.writeln("<a><li><span style=\"color:#E53333;\"><i class=\"fa fa-exclamation-triangle\" aria-hidden=\"true\"></i> 什麽样的网站会被取消收录？</span></li></a>");
document.writeln("<a><li>1、无故下链、随意变更友链位置;</li></a>");
document.writeln("<a><li>2、连续一周流量来路过低;</li></a>");
document.writeln("<a><li>3、使用站群技术骗取流量，后台核实为虚假流量；</li></a>");
document.writeln("<a><li>4、网站经管理员巡查发现无法正常访问；</li></a>");
document.writeln("<a><li>5、经用户举报包含假冒本站/恶意代码/虚假信息等内容。</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate\" id=\"contact\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-envelope\" aria-hidden=\"true\"></i> 联络我们</p>");
document.writeln("</div>");
document.writeln("<a><li>关于友情链接及广告刊登的相关事宜，请联繫</li></a>");
document.writeln("<a><li>电子邮箱：<span style=\"color:#003399;\">500dizhi@gmail.com</span></li></a>");
document.writeln("<a><li>如果有一天网站忽然消失，你又想找到我们...</li></a>");
document.writeln("<a><li>请发送任意内容到上述邮箱找到回家的路</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate\" id=\"log\">");
document.writeln("<div class=\"cate_name\">");
document.writeln("<p><i class=\"fa fa-list\" aria-hidden=\"true\"></i> 更新日志</p>");
document.writeln("</div>");
document.writeln("<a><li>03/21/2022：清理了部分违反规定/来路异常/随意安插竟品暗链的垃圾站点；</li></a>");
document.writeln("<a><li>12/12/2021：页面UI改版，更宽视野才能容纳更多资源；</li></a>");
document.writeln("<a><li>05/21/2021：清理了质量较差的导航类站点；</li></a>");
document.writeln("<a><li>02/23/2021：UI细节优化，对优质站点著重推荐；</li></a>");
document.writeln("<a><li>02/19/2021：清理了部分违反规定/来路异常/随意变更友链位置的垃圾站点；</li></a>");
document.writeln("<a><li>06/23/2020：清除了随意变更友链位置的部分垃圾站点；</li></a>");
document.writeln("<a><li>04/17/2020：清除了随意变换友链位置的垃圾站点；</li></a>");
document.writeln("<a><li>03/26/2020：清除了随意变换友链位置的站点；</li></a>");
document.writeln("<a><li>06/10/2019：清理了部分未及时修改我站链接的站点；</li></a>");
document.writeln("<a><li>2018：网站全新改版上线</li></a>");
document.writeln("<br class=\"clear\">");
document.writeln("</div>");
document.writeln("<div class=\"cate footer\">");
document.writeln("<p>CopyRight&nbsp;&nbsp;©&nbsp;&nbsp;500dh.com</p>");
document.writeln("<p> <i class=\"fa fa-home\" aria-hidden=\"true\"></i> <a href=\"../\" class=\"aboutBtn\" target=\"_blank\">返回首页</a>&nbsp;&nbsp;<i class=\"fa fa-shield\" aria-hidden=\"true\"></i> <a href=\"aq.html\" class=\"aboutBtn\" target=\"_blank\">安全保障</a>&nbsp;&nbsp;<i class=\"fa fa-plus-square\" aria-hidden=\"true\"></i> <a href=\"faq.html\" class=\"aboutBtn\" target=\"_blank\">收录合作</a></p>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<script async src=\"https://www.googletagmanager.com/gtag/js?id=G-HQDVVM82Q2\"></script>");
document.writeln("<script>");
document.writeln("  window.dataLayer = window.dataLayer || [];");
document.writeln("  function gtag(){dataLayer.push(arguments);}");
document.writeln("  gtag(\'js\', new Date());");
document.writeln("");
document.writeln("  gtag(\'config\', \'G-HQDVVM82Q2\');");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("</html>");
